config/routes.rb
Citi::Application.routes.draw do
  resources :searches, only: [:new, :create, :index]
  resources :users do
    # member do
    #     get 'account'
    #   end 
    resources :favorites
      member do
        post 'favorite'
      end  
  end

  get 'account' => 'welcome#account'
  root 'welcome#index'
  
  # get 'searches' => 'searches#index'
  # get 'searches/results' => 'searches#results'
  resource :session, only: [:destroy, :create, :new]
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  validates_presence_of :address, :user_id, :uniqueness => true
  belongs_to :favorable
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true

  has_many :favorites
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = Favorite.where(user_id: params[:user_id])
    render :index
  end


   def create
    @favorite = Favorite.new(favorites_params)
    current_user.favorites << @favorite
    if @favorite.save
      redirect_to user_path(current_user)
      # redirect_to user_favorites_path(current_user)

    else
      redirect_to user_path(current_user)
    end
  end

  private

# this is the white list engineering
  def favorites_params
    params.require(:favorite).permit(:address)
  end

  def favorite?
    favorites[user_id].present? == false
  end


end  



# <ul>
#   <li><h3><%= link_to "Go to Favorites", user_favorites_path(current_user) %></h3></li>
# </ul>

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  # TODO change search index to redirect to a refresh of the results page.
  # TODO add bootstrap
  # TODO add text messaging
  
  def new
    render :new
  end

  def create

    @coordinates = Geocoder.coordinates(params[:address])
    unless @coordinates.nil?

      @coordinates = { latitude: @coordinates[0], longitude: @coordinates[1] }
      @all_citibike_stations = Citibikenyc.stations.values[2]

      available_stations_for_docks = @all_citibike_stations.reject { |d| d["availableDocks"] == 0 }

      available_stations_for_bikes = @all_citibike_stations.reject { |d| d["availableBikes"] == 0 } 

      @winning_dock_station = available_stations_for_docks.min_by do |station|
        distance_x = @coordinates[:longitude] - station["longitude"]
        distance_y = @coordinates[:latitude] - station["latitude"]
        Math.hypot( distance_x, distance_y )
      end 

      @winning_bike_station = available_stations_for_bikes.min_by do |station|
        distance_x = @coordinates[:longitude] - station["longitude"]
        distance_y = @coordinates[:latitude] - station["latitude"]
        Math.hypot( distance_x, distance_y )
        end 

########## next closest station logic ##############

      if @winning_bike_station["label"] == @winning_dock_station["label"]
        id = @winning_bike_station["nearbyStations"][0]["id"] 
        @next_best_station = @all_citibike_stations.select do |station| station["id"] == id
      end
    end

     render :results
    else
     render erb: "<%= debug Geocoder.coordinates(params[:address]) %>"  
    end
  end

  def index
    redirect_to new_search_path
  end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    # authenticate that user/pass combo is legit
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to new_search_path
    else
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  self.before_action( :authenticated!, :set_user, :authorized!, except: [:new, :create] )

  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    # can't do a redirect or else we'll lose our new object. must use render: new
    # need this when you're grabbing user input to create a new model.
    @user = User.new(user_params)
    # @user = User.find(params[:id])

    if @user.save
      redirect_to user_path(@user) 
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end 

  def destroy
    if @user.destroy
      redirect_to new_user_path
    else 
      render :edit
    end
  end

private

# this is the white list engineering
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def logged_in?
    session[:user_id].present?
  end

# this checks for authentication, if not logged in, kick them back to log in page.

  def set_user
    @user = User.find(params[:id])
  end

# prevents users from tampering or seeing with other user accounts. is the user that's logged in, the same as the resource they're trying to access? if not, send them back to their page.
  def authorized!
    unless @user.id == session[:user_id]
      redirect_to user_path(session[:user_id])
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    render :index
  end  

  def account
    render :account
  end

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id].present?
  end

  def authenticated!
    unless logged_in?
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

 def favorites?
    @favorites[:user_id] == nil
  end
end

app/views/favorites/index.html.erb
<div class="container"></div>
  <h2>Saved Destinations</h2>
  <div class="well">
    <% @favorites.each do |favorite| %>
    <ul>
       <li><%=  "#{favorite.address}" %></li>
    <% end %>
    </ul>
 </div> 
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
<!--     <a class="navbar-brand" href="#">Brand</a> -->
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
            <% if logged_in? %>
            <li><%= link_to "Awesome Citi", root_path %> </li>
            <li><%= link_to "My Account", account_path %> </li>
            <li><%= link_to "New Search", new_search_path %> </li>
            <li><%= link_to "Saved Destinations", user_path(current_user) %></li>
            <li><a href="http://citibikenyc.com/stations"target="_blank">Station Map</a></li>
            <li><%= link_to 'Logout', session_path, :method => :delete %> </li>
            <% end %>
          </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesome Citi</title>
  <script>$('.dropdown-toggle').dropdown();</script>
   <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render 'layouts/header'%>
<div class="container">
  <%= yield %>
</div>
<footer>
</footer>
</div>
</body>
</html>

      

app/views/searches/index.html.erb
<div class="container">

<div class="results">
  <%  unless @coordinates.nil? %>
  <ul>
    <li><h3><%= "Closest dock: "%></h3></li>
    <li><h3><%="#{@winning_dock["label"]} has #{@winning_dock["availableDocks"] } dock(s) available. Huzzah!!" %></h3></li>
  </ul>
  <% end  %>
</div>


 <div class="form">
    <%= form_tag user_favorites_path(current_user), :method => :post do %>
    <%= hidden_field_tag "favorite[address]", params[:address]%>
    <%= submit_tag "Save Search to Favorites!" %>
    <% end %>
</div>


<h1>Find docks near your destination:</h1>  

 <div class="form">
    <%= form_tag searches_path, :method => :get do %>   
    <%= text_field_tag :address, params[:address], placeholder: 'street city and zip...'%>  
    <%= submit_tag "Go", :name => nil %>  
    <% end %>  
</div>

<ul>
  <li><h3><%= link_to "New Search", searches_path %></h3></li>
  <li><h3><%= link_to "Go to Favorites", user_path(current_user) %></h3></li>
</ul>

app/views/searches/new.html.erb
<div class="container">
  <div class="well">
    <div class="search_title">
      <h7>Search for the nearest available bike or dock:</h7>  
    </div>
     <div class="form">
        <%= form_tag searches_path, :method => :post do %>  
        <%= text_field_tag :address, params[:address], placeholder: 'street city and zip...'%>  
        <%= submit_tag "Go", :class => 'go' %>   
        <% end %>  
     </div> 
</div>

  <div class="saved">
    <h6><%= link_to "Go to Saved Destinations", user_path(current_user) %></h6>
  </div>

</div>

app/views/searches/results.html.erb
<div class="well">
    <div class="results">
      <% unless @coordinates.nil? %>
        
        <ul>
          <% if @winning_bike_station["label"] == @winning_dock_station["label"]  %> 
          <li><%= "CityBike Station:"%><address><%= "#{@winning_bike_station["label"].gsub("Broadway & W 24 St","1107 Broadway")}"%></address></li>
          <li><%="Docks: #{@winning_bike_station["availableDocks"] }.  Bikes: #{@winning_bike_station["availableBikes"] }"  %></li>
        </ul>
        <% else %>
        <ul>
          <li><%= "Docks:"%><address><%="#{@winning_dock_station["label"].gsub("Broadway & W 24 St","1107 Broadway")}"%></address></li>
          <li><%="Available: #{@winning_dock_station["availableDocks"] }" %></li></br>
          <li><%= "Bikes: "%><address><%="#{@winning_bike_station["label"]}"%></address></li>
          <li><%="Available: #{@winning_bike_station["availableBikes"] }" %></li>
        </ul>   
        <% end %>
      <% end  %>

      <!-- next closest staton -->
      <% if @winning_bike_station["label"] == @winning_dock_station["label"] %>
        <ul>  
          <li>Next closest station:</li>       
          <li><address><%= "#{@next_best_station[0]["label"].gsub("Broadway & W 24 St","1107 Broadway")}"%></address></li>
          <li><%= "Docks: #{@next_best_station[0]["availableDocks"]}.  Bikes: #{@next_best_station[0]["availableBikes"]}" %></li>
        <ul>
      <% end %>    
    </div> <!-- results -->

    <!-- save this destination -->
    <div class="destination">
        <%= form_tag user_favorites_path(current_user), :method => :post do %>
        <%= hidden_field_tag "favorite[address]", params[:address]%>
        <%= submit_tag "Save This Destination", :class => 'saved_destination', :name => :address %> 
        <% end %>
    </div>

    <div class="new_search">
        <h6><%= link_to "New Search", new_search_path %></h6>
    </div>  
</div>

<script>
 $(document).ready(function () {
    //Convert address tags to google map links - Copyright Michael Jasper 2011
    $('address').each(function () {
        var link = "<a href='http://maps.google.com/maps?q=" + encodeURIComponent( $(this).text() ) + " NY" + "' target='_blank'>" + $(this).text() + "</a>";
        $(this).html(link);
    });
}); 
</script>

app/views/users/_form.html.erb
<div class="form">
  <% unless @user.errors.none? %>
    <% @user.errors.full_messages.each do |msg| %> 
    <%= msg %>
    <% end %>
  <% end %>
<ul>
  <%= form_for @user do |f| %>
    <%= f.label :username %></br>
    <%= f.text_field :username, :class => 'field' %></br>
    <%= f.label :email %></br>
    <%= f.email_field :email, :class => 'field' %></br>
    <%= f.label :password %></br>
    <%= f.password_field :password, :class => 'field' %></br>
    <%= f.label :password_confirmation %></br>
    <%= f.password_field :password_confirmation, :class => 'field' %></br>
    <%= f.submit 'Save', :class => 'new_user'%>
  <% end %>
</ul>  
</div>

app/views/users/edit.html.erb
<div class="nav">
  <ul>
    <% if logged_in? %>
    <div class="logo">
    <li><%= link_to "Awesome Citi", root_path %> </li>
    </div>
    <li><%= link_to "My Account", account_path %> </li>
    <li><%= link_to "New Search", new_search_path %> </li>
    <li><%= link_to 'Logout', session_path, :method => :delete %> </li>
    <% end %>
  </ul>
</div>
<h2>Edit Your New Info:</h2>
<%= render 'form' %>

app/views/users/new.html.erb
<div class="nav"> 
    <ul>
      <li><%= link_to "Awesome Citi", root_path %> </li>
    </ul>
</div> 

<h2>Create an account:</h2>
 
  <%= render 'form' %>

app/views/users/show.html.erb
<h2>Your Saved Destinations:</h2>
  <ul>
    <% @user.favorites.each do |favorite| %>
    <%= form_tag searches_path, :method => :post do %>
    <li><%= submit_tag "#{favorite.address}", :class => 'saved_destination', :name => :address %></li>
    <% end %>
    <% end %>
  </ul>


<div class="new_search">
  <h6><%= link_to "New Search", new_search_path %> </h6>
</div>

app/views/welcome/account.html.erb
<div class="well">
  <div class="account">
     <ul>
      <% if logged_in? %></li>
      <li><%= link_to "Edit My Account", edit_user_path(current_user) %></li>
      <li><%= link_to "Delete My Account", user_path(current_user), :method => :delete %></li>
      <li><%= link_to "Saved Destinations", user_path(current_user) %></li>
      <li><%= link_to 'Logout', session_path, :method => :delete %></li>
      <% end %>
    </ul>
  </div>

app/views/welcome/index.html.erb
<!--   <div class="twitter">
    <ul> -->

<!--       <li><a href="https://twitter.com/awesomeciti"><img src="http://a1.twimg.com/profile_images/568641116/french.jpg" alt="citibird" height="120" width="180"></a></li>
      <li>Commute with us on Twitter.</li>
    </ul>  
  </div> -->

<div class="well"> 
  <ul>
    <h1>AWESOME CITY / NYC</h1>
    <h3>I can't find a dock you say.</h3>
    <h3>There's an app for that we say.</h3>
   </ul> 
</div>    

    <% unless logged_in?  %> 
      <h2><%= link_to "Log In", new_session_path %> |
      <%= link_to "Create Account", new_user_path %>
      </h2>
    <% end  %>


    <% if logged_in? %>
      <h2>
      <%= link_to "New Search", new_search_path %> |
      <%= link_to 'Logout', session_path, :method => :delete %>
      </h2> 
    <% end %>